language: ruby
rvm:
- 2.1.3
env:
  global:
    secure: iK4b0iIdLDwwj5qA4A1gpleCs/DYeOxfSdRu+RYVvTnxIrwGVBiy5RBqVYT+/t9d+tEfLFFHRPZQzGQQiS7cYr0Wow5+eDhl5r41rYZvVPoKpVACeK+l8hHInvVtqLGDewkrOmxD19OzOuE3jfqkhNk/T7I8ACw1Qr7hG8l4R4g=
deploy:
  provider: rubygems
  gem: factor-connector-web
  api_key:
    secure: mMY5ZBtkbojnbXBLCnMpvdokLoJU+RbeafrQ3CZpOGXK4+mg8hoY79kdNIYNImF4bhOh3G0Ol0ByCsBGcciX1hknWLyrv8ZNNxlhoDLgTozcTIi8Zyd1SkRD360LUxGn5cDOgX+7o226zh6p2B742dVcgIf8Y469cGxT855DpBg=
  on:
    tags: true
    all_branches: true
