language: ruby
rvm:
  - 1.9.3
  - 2.0.0
  - 2.1.3
  - 2.1.5
  - 2.2.0
  - 2.2.1
  - 2.2.2
env:
  matrix:
    secure: iK4b0iIdLDwwj5qA4A1gpleCs/DYeOxfSdRu+RYVvTnxIrwGVBiy5RBqVYT+/t9d+tEfLFFHRPZQzGQQiS7cYr0Wow5+eDhl5r41rYZvVPoKpVACeK+l8hHInvVtqLGDewkrOmxD19OzOuE3jfqkhNk/T7I8ACw1Qr7hG8l4R4g=
deploy:
  provider: rubygems
  gem: factor-connector-web
  api_key:
    secure: eqUKqAmRw1N7pxHifyMIMecK7llXIAd8owX6MQ8CKJrqmg/1r9vo1XbOc5K9nmqSGBtrDNPWt73LFBpKICBKgiKHC+0D/Yuf1uRtVtgOx3dycy3Kbx+YXiTNgBHGIOtcaC05KOpm6EaC2qmwE6Cgd4fmFVZO3GjWe/aMeDUpzGg=
  on:
    tags: true
    all_branches: true
