language: ruby
rvm:
  - 2.1.9
  - 2.2.5
  - 2.3.1
before_install:
  - wget https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-linux-amd64.zip
  - unzip ./ngrok-stable-linux-amd64.zip
  - set PATH=%PATH%;$(pwd)/ngrok