language: ruby
rvm:
  - 1.9.3
  - 2.0.0
  - 2.1.3
  - 2.1.5
  - 2.2.0
  - 2.2.1
  - 2.2.2
before_install:
  - wget https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-linux-amd64.zip
  - unzip ./ngrok.zip
  - set PATH=%PATH%;$(pwd)/ngrok/ngrok